version: '3.8'

services:
  web:
    build: .
    container_name: Flask_app
    command: gunicorn --bind 0.0.0.0:5000 app:app
    environment:
      - DATABASE_URL=postgresql://hello_flask:hello_flask@db:5432/Pharmacies-Chain
    volumes:
      - /dbpy_webapp:/usr/src/app/
    ports:
      - 5000:5000
    links:
      - db:db
    restart: always
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: hello_flask
      POSTGRES_PASSWORD: hello_flask
      POSTGRES_DB: Pharmacies-Chain
    volumes: 
      - ./SQL_Part2.txt:/docker-entrypoint-initdb.d/init.sql
      - postgresDB:/var/lib/postgresql/data

volumes:
  postgresDB:
