version: '3.8'

services:
  app:
    build: .
    container_name: Flask
    #command: gunicorn --bind 0.0.0.0:5000 app:app
    environment:
      - DATABASE_URL=postgresql://hello_flask:hello_flask@db:5432/Pharmacies-Chain
      - SQLALCHEMY_DATABASE_URI=postgresql://hello_flask:hello_flask@db:5432/Pharmacies-Chain
      - SQLALCHEMY_TRACK_MODIFICATIONS = False
    volumes:
      - /dbpy_webapp:/usr/src/app/
    ports:
      - 5000:5000
    links:
      - db:db
    restart: always
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: Postgres
    environment:
      POSTGRES_USER: hello_flask
      POSTGRES_PASSWORD: hello_flask
      POSTGRES_DB: Pharmacies-Chain
    volumes: 
      - ./SQL_Part2.txt:/docker-entrypoint-initdb.d/init.sql
  proxy:
    build: nginx
    container_name: Nginx
    restart: always
    ports:
      - 10000:10000
    depends_on:
      - app
