version: '3.8'

services:
  app:
    build: .
    container_name: Flask
    environment:
      - DATABASE_URL=db://hello_flask:hello_flask@db:5432/Pharmacies-Chain
      - SQLALCHEMY_DATABASE_URI=postgresql://hello_flask:hello_flask@db:5432/Pharmacies-Chain
      - SQLALCHEMY_TRACK_MODIFICATIONS = False
    ports:
      - 8000:8000
    links:
      - db:db
    restart: always
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: Postgres
    environment:
      POSTGRES_USER: hello_flask
      POSTGRES_PASSWORD: hello_flask
      POSTGRES_DB: Pharmacies-Chain
    volumes: 
      - ./SQL_Part2.txt:/docker-entrypoint-initdb.d/init.sql
